{% set name = "turfpy" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c02848952512f9cdbf144dcb342e413bc7289c79e62712520e7ff2978d7b93f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - geojson
    - numpy
    - scipy
    - shapely

test:
  imports:
    - turfpy
    - turfpy.dev_lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/omanges/turfpy
  summary: This is Python library for performing geo spatial data analysis.
  license: MIT
  # License file manually packaged. See: https://github.com/omanges/turfpy/pull/48
  license_file: LICENSE

  dev_url: https://github.com/omanges/turfpy
  doc_url: https://turfpy.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - omanges
    - sackh
