{% set name = "turfpy" %}
{% set version = "0.0.8" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af7670ac4736b916a90885c8944e1f76c4f386e3f04ffe8a3bafe160ccb1e4e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - geojson ==3.1.0
    - geopandas ==1.0.1
    - shapely ==2.0.6
    - scipy ==1.14.1
    - numpy ==1.26.4

test:
  imports:
    - turfpy
    - turfpy.dev_lib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/omanges/turfpy
  summary: A Python library for performing geospatial data analysis which reimplements turf.js.
  license: MIT
  license_file: LICENSE

  dev_url: https://github.com/omanges/turfpy
  doc_url: https://turfpy.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - omanges
    - sackh
