{% set name = "turfpy" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e12aeb398ab4a7a2a459e39f3beabb6d89d1d11b0713bb7f9606cebec0e0147

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - geojson
    - numpy
    - scipy
    - shapely

test:
  imports:
    - turfpy
    - turfpy.dev_lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/omanges/turfpy
  summary: This is Python library for performing geo spatial data analysis.
  license: MIT
  license_file: LICENSE

  dev_url: https://github.com/omanges/turfpy
  doc_url: https://turfpy.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - omanges
    - sackh
